
ManyBoxPlot(' Alpha', chanLocs,sumBounceOutOfPitAlpha,' BounceOutOfPit', sumBreakingBoxesAlpha ,' BreakingBox' , sumBreakingChanceBoxesAlpha ,' BreakingChanceBox', sumBreakingEmptyBoxesAlpha, ' BreakingEmptyBox' , sumChanceBoxEnemyAlpha, ' ChanceBoxEnemy' , sumChanceBoxWithCoinAlpha, ' ChanceBoxCoin', sumChanceBoxWithFlowerAlpha, 'ChanceBoxFlower', sumChanceBoxWithMushroomAlpha, ' ChanceBoxMushroom' , sumCollectingCoinAlpha, ' CollectingCoin', sumCollidingWithItemsAlpha, ' CollidingWithItems' , sumDeathByEnemyAlpha, ' DeathByEnemy', sumDeathByPitAlpha, ' DeathByPit', sumDevovleAlpha, ' Devolve', sumEmptyBoxEnemyAlpha, ' EmptyBoxEnemy', sumEmptyBoxWithCoinAlpha, ' EmptyBoxCoin', sumEmptyBoxWithFlowerAlpha, ' EmptyBoxFlower', sumEmptyBoxWithMushroomAlpha, ' EmptyBoxMushroom', sumEvolvingAlpha, ' Evolving', sumEvovleByEnemyAlpha, ' EvolveByEnemy', sumItemEmptyBoxAlpha, 'EmptyBoxItem', sumJumpAtEdgeAlpha, ' JumpAtEdge', sumJumpFailedAlpha, ' JumpFailed', sumJumpSuccessAlpha, ' JumpSuccess', sumKillingEnemyAlpha, ' killingEnemy', sumKillWithFireballAlpha, ' killWithFireball', sumKillWithShellAlpha, ' KillWithShell', sumKillWithStompAlpha, ' KillWithStomp', sumLosingLevelAlpha, ' LosingLevel', sumpickUpCoinAlpha, ' pickUpCoin', sumpickUpFlowerAlpha, ' pickUpFlower', sumpickUpMushroomAlpha, ' pickUpMushroom', sumSurprisesAlpha, 'surprises', sumWinningLevelAlpha, 'WinningLevel' )

ManyBoxPlot(' Beta', chanLocs,sumBounceOutOfPitBeta,' BounceOutOfPit', sumBreakingBoxesBeta ,' BreakingBox' , ...
    sumBreakingChanceBoxesBeta ,' BreakingChanceBox', sumBreakingEmptyBoxesBeta, ' BreakingEmptyBox' , ...
    sumChanceBoxEnemyBeta, ' ChanceBoxEnemy' , sumChanceBoxWithCoinBeta, ' ChanceBoxCoin', ...
    sumChanceBoxWithFlowerBeta, 'ChanceBoxFlower', sumChanceBoxWithMushroomBeta, ' ChanceBoxMushroom' , ...
    sumCollectingCoinBeta, ' CollectingCoin', sumCollidingWithItemsBeta, ' CollidingWithItems' , ...
    sumDeathByEnemyBeta, ' DeathByEnemy', sumDeathByPitBeta, ' DeathByPit', sumDevovleBeta, ' Devolve', ...
    sumEmptyBoxEnemyBeta, ' EmptyBoxEnemy', sumEmptyBoxWithCoinBeta, ' EmptyBoxCoin', suEmptyBoxWithFlowerBeta,...
    ' EmptyBoxFlower', sumEmptyBoxWithMushroomBeta, ' EmptyBoxMushroom', sumEvolvingBeta, ...
    ' Evolving', sumEvovleByEnemyBeta, ' EvolveByEnemy', sumItemEmptyBoxBeta, 'EmptyBoxItem', ...
    sumJumpAtEdgeBeta, ' JumpAtEdge', sumJumpFailedBeta, ' JumpFailed', sumJumpSuccessBeta, ' JumpSuccess',...
    sumKillingEnemyBeta, ' killingEnemy', sumKillWithFireballBeta, ' killWithFireball', ...
    sumKillWithShellBeta, ' KillWithShell', sumKillWithStompBeta, ' KillWithStomp',...
    sumLosingLevelBeta, ' LosingLevel', sumpickUpCoinBeta, ' pickUpCoin', sumpickUpFlowerBeta, ' pickUpFlower',...
    sumpickUpMushroomBeta, ' pickUpMushroom', sumSurprisesBeta, 'surprises', sumWinningLevelBeta, 'WinningLevel' )

ManyBoxPlot(' Delta', chanLocs,sumBounceOutOfPitDelta,' BounceOutOfPit', sumBreakingBoxesDelta ,' BreakingBox' , ...
    sumBreakingChanceBoxesDelta ,' BreakingChanceBox', sumBreakingEmptyBoxesDelta, ' BreakingEmptyBox' , ...
    sumChanceBoxEnemyDelta, ' ChanceBoxEnemy' , sumChanceBoxWithCoinDelta, ' ChanceBoxCoin', ...
    sumChanceBoxWithFlowerDelta, 'ChanceBoxFlower', sumChanceBoxWithMushroomDelta, ' ChanceBoxMushroom' , ...
    sumCollectingCoinDelta, ' CollectingCoin', sumCollidingWithItemsDelta, ' CollidingWithItems' , ...
    sumDeathByEnemyDelta, ' DeathByEnemy', sumDeathByPitDelta, ' DeathByPit', sumDevovleDelta, ' Devolve', ...
    sumEmptyBoxEnemyDelta, ' EmptyBoxEnemy', sumEmptyBoxWithCoinDelta, ' EmptyBoxCoin', sumEmptyBoxWithFlowerDelta,...
    ' EmptyBoxFlower', sumEmptyBoxWithMushroomDelta, ' EmptyBoxMushroom', sumEvolvingDelta, ...
    ' Evolving', sumEvovleByEnemyDelta, ' EvolveByEnemy', sumItemEmptyBoxDelta, 'EmptyBoxItem', ...
    sumJumpAtEdgeDelta, ' JumpAtEdge', sumJumpFailedDelta, ' JumpFailed', sumJumpSuccessDelta, ' JumpSuccess',...
    sumKillingEnemyDelta, ' killingEnemy', sumKillWithFireballDelta, ' killWithFireball', ...
    sumKillWithShellDelta, ' KillWithShell', sumKillWithStompDelta, ' KillWithStomp',...
    sumLosingLevelDelta, ' LosingLevel', sumpickUpCoinDelta, ' pickUpCoin', sumpickUpFlowerDelta, ' pickUpFlower',...
    sumpickUpMushroomDelta, ' pickUpMushroom', sumSurprisesDelta, 'surprises', sumWinningLevelDelta, 'WinningLevel' )

ManyBoxPlot(' Theta', chanLocs,sumBounceOutOfPitTheta,' BounceOutOfPit', sumBreakingBoxesTheta ,' BreakingBox' , ...
    sumBreakingChanceBoxesTheta ,' BreakingChanceBox', sumBreakingEmptyBoxesTheta, ' BreakingEmptyBox' , ...
    sumChanceBoxEnemyTheta, ' ChanceBoxEnemy' , sumChanceBoxWithCoinTheta, ' ChanceBoxCoin', ...
    sumChanceBoxWithFlowerTheta, 'ChanceBoxFlower', sumChanceBoxWithMushroomTheta, ' ChanceBoxMushroom' , ...
    sumCollectingCoinTheta, ' CollectingCoin', sumCollidingWithItemsTheta, ' CollidingWithItems' , ...
    sumDeathByEnemyTheta, ' DeathByEnemy', sumDeathByPitTheta, ' DeathByPit', sumDevovleTheta, ' Devolve', ...
    sumEmptyBoxEnemyTheta, ' EmptyBoxEnemy', sumEmptyBoxWithCoinTheta, ' EmptyBoxCoin', sumEmptyBoxWithFlowerTheta,...
    ' EmptyBoxFlower', sumEmptyBoxWithMushroomTheta, ' EmptyBoxMushroom', sumEvolvingTheta, ...
    ' Evolving', sumEvovleByEnemyTheta, ' EvolveByEnemy', sumItemEmptyBoxTheta, 'EmptyBoxItem', ...
    sumJumpAtEdgeTheta, ' JumpAtEdge', sumJumpFailedTheta, ' JumpFailed', sumJumpSuccessTheta, ' JumpSuccess',...
    sumKillingEnemyTheta, ' killingEnemy', sumKillWithFireballTheta, ' killWithFireball', ...
    sumKillWithShellTheta, ' KillWithShell', sumKillWithStompTheta, ' KillWithStomp',...
    sumLosingLevelTheta, ' LosingLevel', sumpickUpCoinTheta, ' pickUpCoin', sumpickUpFlowerTheta, ' pickUpFlower',...
    sumpickUpMushroomTheta, ' pickUpMushroom', sumSurprisesTheta, 'surprises', sumWinningLevelTheta, 'WinningLevel' )

ManyBoxPlot(' Gamma', chanLocs,sumBounceOutOfPitGamma,' BounceOutOfPit', sumBreakingBoxesGamma ,' BreakingBox' , ...
    sumBreakingChanceBoxesGamma ,' BreakingChanceBox', sumBreakingEmptyBoxesGamma, ' BreakingEmptyBox' , ...
    sumChanceBoxEnemyGamma, ' ChanceBoxEnemy' , sumChanceBoxWithCoinGamma, ' ChanceBoxCoin', ...
    sumChanceBoxWithFlowerGamma, 'ChanceBoxFlower', sumChanceBoxWithMushroomGamma, ' ChanceBoxMushroom' , ...
    sumCollectingCoinGamma, ' CollectingCoin', sumCollidingWithItemsGamma, ' CollidingWithItems' , ...
    sumDeathByEnemyGamma, ' DeathByEnemy', sumDeathByPitGamma, ' DeathByPit', sumDevovleGamma, ' Devolve', ...
    sumEmptyBoxEnemyGamma, ' EmptyBoxEnemy', sumEmptyBoxWithCoinGamma, ' EmptyBoxCoin', sumEmptyBoxWithFlowerGamma,...
    ' EmptyBoxFlower', sumEmptyBoxWithMushroomGamma, ' EmptyBoxMushroom', sumEvolvingGamma, ...
    ' Evolving', sumEvovleByEnemyGamma, ' EvolveByEnemy', sumItemEmptyBoxGamma, 'EmptyBoxItem', ...
    sumJumpAtEdgeGamma, ' JumpAtEdge', sumJumpFailedGamma, ' JumpFailed', sumJumpSuccessGamma, ' JumpSuccess',...
    sumKillingEnemyGamma, ' killingEnemy', sumKillWithFireballGamma, ' killWithFireball', ...
    sumKillWithShellGamma, ' KillWithShell', sumKillWithStompGamma, ' KillWithStomp',...
    sumLosingLevelGamma, ' LosingLevel', sumpickUpCoinGamma, ' pickUpCoin', sumpickUpFlowerGamma, ' pickUpFlower',...
    sumpickUpMushroomGamma, ' pickUpMushroom', sumSurprisesGamma, 'surprises', sumWinningLevelGamma, 'WinningLevel' )